spring:
  application:
    name: backend
  datasource:
    url: jdbc:mysql://localhost:3306/cloudBalance
    username: root
    password: Root@123.
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  security:
    user:
      name: "mohit"
      password: "mohit123"
  jwt:
    secretKey: "$#2cloud@#$#$@^&^&#&%#@%@#$Balance$$*!%^#*O^(^%*^&$)Project"

snowflake:
  url: https://driwnxq-ye10711.snowflakecomputing.com
  user: MOHIT
  password: Mnimohitbisht7011.
  role: ACCOUNTADMIN
  db: AWSCOSTANALYTICS
  schema: PUBLIC
